package lexico

enum class TipoToken {
    RESERVADA, IDENTIFICADOR, NUMERO_ENTERO, NUMERO_REAL,
    CADENA, ASIGNACION, OPERADOR, DELIMITADOR,
    PARENTESIS_A, PARENTESIS_C, LLAVE_A, LLAVE_C,
    PUNTO_COMA, COMA, FIN_ARCHIVO, DESCONOCIDO
}
